app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('allauth.urls')),
    path('members/', include('members.urls')),
    path('hotels/', include('hotels.urls')),
]

app/products/models.py
from django.conf import settings
from django.db import models
from region.models import City


class ProductBase(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField(blank=True)
    date = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class TicketInfo(ProductBase):
    region = models.ManyToManyField(
        City,
        related_name='',
    )


class GuideTourInfo(ProductBase):
    name = models.CharField(max_length=5)
    region = models.ManyToManyField(
        City,
        related_name='',
    )


class ActivityInfo(ProductBase):
    region = models.ManyToManyField(
        City,
        related_name='',
    )


class Comment(models.Model):
    ticket = models.ForeignKey(
        TicketInfo,
        on_delete=models.CASCADE,
        null=True,
        related_name='comments_by_tickets',
    )
    guide = models.ForeignKey(
        GuideTourInfo,
        on_delete=models.CASCADE,
        null=True,
        related_name='comments_by_guide_tour',
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.author.username}님의 댓글(후기)'


class TicketPriceInfo(models.Model):
    ticket = models.ForeignKey(
        TicketInfo,
        on_delete=models.CASCADE,
        null=True,
        related_name='ticket_price',
    )
    date = models.IntegerField()
    price = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f'{self.ticket}의 가격 : {self.price}'


class GuidePriceInfo(models.Model):
    guide = models.ForeignKey(
        GuideTourInfo,
        on_delete=models.CASCADE,
        null=True,
        related_name='guide_price',
    )
    date = models.IntegerField()
    price = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f'{self.guide}의 가격 : {self.price}'

app/products/models/product_city_list.py
from django.conf import settings
from django.db import models

from products import crawler
from region.models import Country

__all__ = (
    'PopularCity',
)


class PopularCity(models.Model):
    popular_image = models.CharField(max_length=500)
    popular_city_name = models.CharField(max_length=50)

    # crwaler를 실행하여 popular_city_list를 반환함
    def get_popular_city_crawler(self):
        popular_city_list = crawler.GetPopularCity().get_popular_city_list()
        return popular_city_list

    # 위 함수를 실행시켜 얻은 popular_city_list를 통해 각 유명도시 인스턴스 생성
    def create_popular_city(self):
        city_list = self.get_popular_city_crawler()
        for city in city_list:
            PopularCity.objects.create(
                popular_image=city['popular_image'],
                popular_city_name=city['popular_city_name'],
            )

app/products/models/productinfo.py
from django.conf import settings
from django.db import models

from products import crawler
from region.models import City, Country


class ProductInfo(models.Model):
    city = models.ForeignKey(
        City,
        on_delete=models.CASCADE,
    )
    country = models.ForeignKey(
        Country,
        on_delete=models.CASCADE,
    )

    def get_product_list_crawler(self):

        product_list = crawler.ProductList(city=self.city, country=self.country)
        product_list.get_product_list()

        result = product_list.product_list
        return result

    def create_product(self):
        products_list = self.get_product_list_crawler()

        for product in products_list:
            Product.objects.create(
                city=product.city,
                country=product.country,
                thumbnail=product.thumbnail,
                tour_name=product.tour_name,
                title=product.title,
                review=product.review,
                price=product.price,
                category=product.category,
                meta_info=product.meta_info,
                no=product.no,
            )


class Product(models.Model):
    city = models.ForeignKey(
        City,
        on_delete=models.CASCADE,
    )
    country = models.ForeignKey(
        Country,
        on_delete=models.CASCADE,
    )
    tour_name = models.CharField(max_length=255)
    thumbnail = models.CharField(max_length=500)
    title = models.CharField(max_length=255)
    review = models.CharField(max_length=255)
    price = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    meta_info = models.CharField(max_length=255, blank=True)
    no = models.IntegerField(blank=True)

    def get_product_detail_crawler(self):

        product_detail_list = crawler.GetProductDetail(no=self.no)
        result = product_detail_list.get_product_detail()

        return result

    def create_product_detail(self):
        products_detail = self.get_product_detail_crawler()
        ProductDetail.objects.create(
            product=self,
            title=products_detail['title'],
            region=products_detail['region'],
            review=products_detail['review'],
            price=products_detail['price'],
            product_type=products_detail['product_type'],
            meet_time=products_detail['meet_time'],
            time=products_detail['time'],
            language=products_detail['language'],
            product_type_a=products_detail['product_type_a'],
            meet_time_a=products_detail['meet_time_a'],
            time_a=products_detail['time_a'],
            language_a=products_detail['language_a'],
            guide_name=products_detail['guide_name'],
            guide_desc=products_detail['guide_desc'],
            introduce=products_detail['introduce'],
            introduce_desc=products_detail['introduce_desc'],
        )


class ProductDetail(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
    )
    title = models.CharField(max_length=255)
    region = models.CharField(max_length=100)
    review = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    product_type = models.CharField(max_length=25, blank=True)
    meet_time = models.CharField(max_length=25, blank=True)
    time = models.CharField(max_length=25, blank=True)
    language = models.CharField(max_length=25, blank=True)
    product_type_a = models.CharField(max_length=25, blank=True)
    meet_time_a = models.CharField(max_length=25, blank=True)
    time_a = models.CharField(max_length=25, blank=True)
    language_a = models.CharField(max_length=25, blank=True)
    guide_name = models.CharField(max_length=255)
    guide_desc = models.TextField()
    introduce = models.CharField(max_length=1000)
    introduce_desc = models.TextField()



#     class Meta:
#         abstract = True
#
#
# class ProductDetail(ProductDetailBase):
#     pass
#
#
# class ProductTicketDetail(ProductDetailBase):
#     region = models.ManyToManyField(
#         City,
#         related_name='city_ticket',
#     )
#     select_option = models.CharField(max_length=255)
#     info_photo = models.ImageField(upload_to='information', blank=True)
#     information = models.TextField()
#
#
# class ProductGuideTourDetail(ProductDetailBase):
#     region = models.ManyToManyField(
#         City,
#         related_name='city_guide',
#     )
#     tour_terms = models.TextField()
#     course_image = models.ImageField(upload_to='course_image', blank=True)
#     course_text = models.TextField(blank=True)
#
#
# class ProductActivityDetail(ProductDetailBase):
#     region = models.ManyToManyField(
#         City,
#         related_name='city_activity',
#     )
#     course_image = models.ImageField(upload_to='course_image', blank=True)
#     course_text = models.TextField(blank=True)


class Comment(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.author.username}님의 댓글(후기)'


class PriceInfoBase(models.Model):
    date = models.IntegerField()
    price = models.CharField(max_length=255, blank=True)

    class Meta:
        abstract = True


# class TicketPriceInfo(PriceInfoBase):
#     ticket = models.ForeignKey(
#         TicketInfo,
#         on_delete=models.CASCADE,
#         null=True,
#         related_name='ticket_price',
#     )
#
#     def __str__(self):
#         return f'{self.ticket}의 가격 : {self.price}'
#
#
# class GuidePriceInfo(PriceInfoBase):
#     guide = models.ForeignKey(
#         GuideTourInfo,
#         on_delete=models.CASCADE,
#         null=True,
#         related_name='guide_price',
#     )
#
#     def __str__(self):
#         return f'{self.guide}의 가격 : {self.price}'
#
#
# class ActivityPriceInfo(PriceInfoBase):
#     activity = models.ForeignKey(
#         ActivityInfo,
#         on_delete=models.CASCADE,
#         null=True,
#         related_name='activity_price',
#     )
#
#     def __str__(self):
#         return f'{self.activity}의 가격 : {self.price}'

app/region/models.py
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.name}'


class City(models.Model):
    name = models.CharField(max_length=255)
    country = models.ForeignKey(
        Country,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f'{self.name}'

app/products/urls/views.py
from django.urls import path

from products import views

urlpatterns = [
    path('', views.popular_city_list, name='popular-city-list'),
    path('search_result/', views.product_search, name='product-search'),
    path('product_list/', views.product_list, name='product-list'),
    path('product_list/<str:country>/<str:city>/', views.product_city_content, name='product-city-content'),
    path('product_list/<str:country>/<str:city>/<int:pk>/', views.product_detail, name='product-detail'),
]

app/products/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, HttpResponseRedirect

from products.crawler import GetProductDetail
from products.models import PopularCity
from products.models.productinfo import Product, ProductInfo, ProductDetail
from region.models import Country, City
from wishlist.models import WishList


def popular_city_list(request):

    if len(PopularCity.objects.all()) == 0:
        cities = PopularCity.objects.create()
        cities.create_popular_city()
    popular_cities = PopularCity.objects.all()[1:]
    context = {
        'popular_cities': popular_cities,
    }
    return render(request, 'products/popular_city_list.html', context)


def product_list(request):

    countries = Country.objects.all()
    context = {
        'countries': countries,
    }
    return render(request, 'products/product_list.html', context)


def product_city_content(request, country, city):
    products = Product.objects.filter(country=Country.objects.get(name=country)).filter(
        city=City.objects.get(name=city))
    if len(products) == 0:
        product_info = ProductInfo.objects.create(country=Country.objects.get(name=country), city=City.objects.get(name=city))
        product_info.create_product()

    products = Product.objects.filter(country=Country.objects.get(name=country)).filter(
        city=City.objects.get(name=city))


    context = {
        'products':products,
        # 'wishlist':wishlist,
    }
    return render(request, 'products/products_city_content.html', context)


def product_detail(request, country, city, pk):
    product = ProductDetail.objects.filter(
        product__country__name__contains=country,
        product__city__name__contains=city,
        product=Product.objects.get(pk=pk)
    )

    if len(product) == 0:
        instance = Product.objects.get(pk=pk)
        instance.create_product_detail()

    product = ProductDetail.objects.filter(
        product__country__name__contains=country,
        product__city__name__contains=city,
        product=Product.objects.get(pk=pk)
    )[0]

    context = {
        'product': product,

    }
    return render(request, 'products/product_detail.html', context)


def product_search(request):
    keyword = request.GET['keyword']
    if keyword:
        results = Product.objects.filter(
            Q(country__name__contains=keyword)|
            Q(city__name__contains=keyword)|
            Q(tour_name__contains=keyword)|
            Q(title__contains=keyword)
        )
        if len(results) == 0:
            return render(request, 'products/products_search_not_found.html')
        else:
            context = {
                'results':results,
            }
            return render(request, 'products/products_search_result.html', context)
    else:
        return redirect('popular-city-list')

app/templates/products/cities_list.html
{% extends 'base.html' %}
{% block content %}

    {% for country in countries %}
        <h3>{{ country }}</h3>
        {% for city in country.city_set.all %}
            <p><a href="{% url 'koreanhotel-list' country=country.name city=city.name %}">{{ city }}</a></p>
        {% endfor %}

    {% endfor %}
    <hr>
{% endblock %}

app/templates/products/popular_city_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container clearfix">
        <p><a href="{% url 'product-list' %}">나라별 투어티켓 보기</a></p>
        <form action="{% url 'product-search' %}" method="GET">
            <div class="input-group mb-3" style="max-width: 800px;">
                <input type="text" class="form-control" placeholder="나라/도시 또는 키워드를 입력하세요"
                       aria-describedby="button-addon2" name="keyword">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">검색</button>
                </div>
            </div>
        </form>
        {% for popular_city in popular_cities %}
            <div class="float-left">
                <div class="card">

                    <a href="{% url 'product-list' %}">
                    <img class="card-img-top" src="{{ popular_city.popular_image }}">
                    <h5 class="card-title" style="text-align: center">{{ popular_city.popular_city_name }}</h5></a>

                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/products/product_detail.html
{% extends 'base.html' %}
{% block content %}
        <div class="card" style="width: 50%; min-width: 600px; margin: auto">
            <div class="card-title">
                <p style="text-align: center"><strong>{{ product.title }}</strong></p>
                <p style="text-align: right">{{ product.region }}</p>
                <p style="text-align: right">{{ product.review }}</p>
            </div>
            <div class="card-body">
                <p>{{ product.product_type }} : {{ product.product_type_a }}</p>
                <p>{{ product.meet_time }} : {{ product.meet_time_a }}</p>
                <p>{{ product.time }} : {{ product.time_a }}</p>
                <p>{{ product.language }} : {{ product.language_a }}</p>
                <p>{{ product.guide_name }}</p>
                <p>{{ product.guide_desc }}</p>
                <p>{{ product.introduce }}</p>
                <p>{{ product.introduce_desc }}</p>

            </div>
        </div>

{% endblock %}

app/templates/products/product_list.html
{% extends 'base.html' %}
{% block content %}

    {% for country in countries %}
        <h2>{{ country }}</h2>
        {% for city in country.city_set.all %}
            <a href="{% url 'product-city-content' country city %}"><p><strong>{{ city }}</strong></p></a>
        {% endfor %}

    {% endfor %}

{% endblock %}

app/templates/products/products.html
{% extends 'base.html' %}
{% block content %}
{% for ticket in ticket_list %}
    <p>{{ koreanhotel.name }}</p>
    <img src="{{ ticket.thumbnail }}" alt="">
    <p>{{ ticket.title }}</p>
    <p>{{ ticket.price }}</p>
{% endfor %}


{% endblock %}

app/templates/products/products_city_content.html
{% extends 'base.html' %}
{% block content %}
    {% for product in products %}
        <a href="{% url 'product-detail' product.country product.city product.pk %}">
            <div class="card" style="width: 50%; min-width: 600px; margin: auto">
                <div class="card-title">
                    <p style="text-align: center"><strong>{{ product.title }}</strong></p>
                    <p style="text-align: right"><strong>{{ product.tour_name }}</strong></p>
                </div>
                <img class="card-img-top" src="{{ product.thumbnail }}" style="width: 100%">
                <div class="card-body">
                    <p>{{ product.review }}</p>
                    <p>가격 : {{ product.price }}</p>
                    <p>티켓종류 : {{ product.category }}</p>
                    <p>기타정보 : {{ product.meta_info }}</p>
                    <p>{{ product.no }}</p>

            </div>
        </div></a>
    {% endfor %}
{% endblock %}

app/templates/products/products_search_not_found.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h2 style="text-align: center">검색 결과를 찾을 수 없습니다.</h2>
    <a style="text-align: center" href="{% url 'popular-city-list' %}"><p>검색 페이지로 돌아가기</p></a>
</div>

{% endblock %}

app/templates/products/products_search_result.html
{% extends 'base.html' %}
{% block content %}
    {% for result in results %}
        <div class="card" style="width: 50%; min-width: 600px; margin: auto">
            <div class="card-title">
                <p style="text-align: center"><strong>{{ result.title }}</strong></p>
                <p style="text-align: right"><strong>{{ result.tour_name }}</strong></p>
            </div>
            <img class="card-img-top" src="{{ result.thumbnail }}" style="width: 100%">
            <div class="card-body">
                <p>{{ result.review }}</p>
                <p>가격 : {{ result.price }}</p>
                <p>티켓종류 : {{ result.category }}</p>
                <p>여행정보 : {{ result.meta_info }}</p>
            </div>
        </div>
    {% endfor %}
{% endblock %}