app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('allauth.urls')),
    path('members/', include('members.urls')),
    path('hotels/', include('hotels.urls')),
]

app/members/urls.py
from django.conf.urls import url
from django.urls import path

from members import views

app_name = 'members'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('facebook-login/', views.facebook_login, name='facebook-login'),
    path('mypage/', views.mypage, name='mypage'),
]

app/members/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    CHOICE_GENDER = (
        ('m', '남성'),
        ('f', '여성'),
        ('x', '선택안함'),
    )
    name = models.CharField(max_length=5)
    introduce = models.TextField(blank=True)
    img_profile = models.ImageField(upload_to='user', blank=True)
    gender = models.CharField(max_length=1, choices=CHOICE_GENDER)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.username

app/members/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

app/members/urls/views.py
from django.conf.urls import url
from django.urls import path

from .. import views

app_name = 'members'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('facebook-login/', views.facebook_login, name='facebook-login'),
    path('mypage/', views.mypage, name='mypage'),
]

app/members/views/activate.py
from django.contrib.auth import get_user_model, login
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from members.tokens import account_activation_token

__all__ = (
    'activate',
)

User = get_user_model()


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return render(request, 'members/user_active_complete.html')
    else:
        return HttpResponse('Activation link is invalid!')

app/members/views/facebook_login.py
from django.contrib.auth import login, get_user_model, authenticate
from django.shortcuts import redirect

User = get_user_model()

__all__ = (
    'facebook_login',
)


def facebook_login(request):

    code = request.GET.get('code')
    user = authenticate(request, code=code, backend='django.contrib.auth.backends.ModelBackend')

    if user is not None:
        login(request, user)
        return redirect('index')
    return redirect('members:login')

app/members/views/login.py
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render

__all__ = (
    'login_view',
)


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            # next = request.GET['next']
            #
            # if next:
            #     return redirect(next)
            return redirect('index')
        else:
            return redirect('members:login')
    else:
        return render(request, 'members/login.html')

app/members/views/logout.py
from django.contrib.auth import logout
from django.shortcuts import redirect

__all__ = (
    'logout_view',
)


def logout_view(request):
    logout(request)
    return redirect('index')

app/members/views/mypage.py
from django.shortcuts import render

from wishlist.models import WishList

__all__ = (
    'mypage',
)

def mypage(request):
    wishlist = WishList.objects.all()
    print(wishlist)
    context = {
        'wishlist': wishlist,
    }
    return render(request, 'members/mypage.html', context)

app/members/views/signup.py
from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

from members.forms import SignupForm
from members.tokens import account_activation_token

__all__ = (
    'signup',
)

User = get_user_model()


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('members/user_activate_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'members/signup_done.html')
    else:
        form = SignupForm()
    return render(request, 'members/signup.html', {'form': form})

app/templates/members/login.html
{% extends 'base.html' %}
{% block content %}
{% load socialaccount %}
    <h1>Login Page</h1>

    <div>
        <form action="" method="POST">
            {% csrf_token %}
            <input type="text" name="username">
            <input type="password" name="password">
            <button type="submit" class="btn btn-info">로그인</button>
        </form>
    </div>

    <div class="btn-wrap">
        <a class="btn-new btn--type-outline btn--width-100 btn-sns" href="{% provider_login_url 'facebook' method='oauth2' %}">
    <img class="icon" src="https://d2yoing0loi5gh.cloudfront.net/assets/kitty/setting/fb-logo@2x-2a65bc6ab97a894a1baeca5b714f4201eb991cfc6d955ef657f86de8e56f89d5.png" width="18">
    <span>페이스북으로 로그인</span>
        </a>
    </div>

    <div class="btn-wrap">
        <a class="btn-new btn--type-outline btn--width-100 btn-sns" href="{% provider_login_url 'naver' method='oauth2' %}">
    <img class="icon" src="https://d2yoing0loi5gh.cloudfront.net/assets/kitty/setting/naver-logo@2x-332865f7b796a02822378e0b61e6dcace93ae9a24abd810cd774a06b5fbcb0b5.png" width="18">
    <span>네이버로 로그인</span>
    </a>
    </div>

{% endblock %}

app/templates/members/mypage.html
{% extends 'base.html' %}
{% block content %}
<h1>My page</h1>
<h3>Wish List</h3>

{% for item in wishlist %}
    <p>{{ item.product.first.title }}</p>
    <img src="{{ item.product.first.thumbnail }}" alt="">

{% endfor %}

{% endblock %}

app/templates/members/signup.html
{% extends 'base.html' %}
{% block content %}
<h1>SignUp Page</h1>
<div>
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.non_field_errors }}
		{% for field in form %}
		<div class="form-group">
			<label for="{{ field.id_for_label }}">{{ field.label }}</label>
			{{ field }}
			{{ field.errors }}
		</div>
		{% endfor %}
		<button type="submit" class="btn btn-primary btn-block">회원가입</button>
	</form>
</div>

{% endblock %}

app/templates/members/signup_done.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
        <h2>회원가입이 완료되었습니다.</h2>
        <h5>메일 인증 후 다시 로그인해주세요.</h5>
    </div>

{% endblock %}

app/templates/members/user_activate_email.html
{% autoescape off %}
{{ user.username }}님 반갑습니다.
다음 주소를 클릭하여 이메일을 인증해 주세요

http://myrealtrip-project.ap-northeast-2.elasticbeanstalk.com{% url 'members:activate' uidb64=uid token=token %}
{% endautoescape %}

app/templates/members/user_active_complete.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}
    <div class="container">
        <div class="spacer_30">&nbsp;</div>
        <div class="spacer_90 hidden-sm hidden-xs">&nbsp;</div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p>이메일 인증이 완료되었습니다. 다시 로그인해주세요!</p>

                        <p><a class="btn btn-primary" href="{% url 'members:login' %}">Log in</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}