app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('allauth.urls')),
    path('members/', include('members.urls')),
    path('hotels/', include('hotels.urls')),
]

app/members/urls.py
from django.conf.urls import url
from django.urls import path

from members import views

app_name = 'members'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('facebook-login/', views.facebook_login, name='facebook-login'),
    path('mypage/', views.mypage, name='mypage'),
]

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MyRealTrip</title>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
</head>
<body>
<nav class="navbar navbar-expand navbar-light bg-light">
    <div class="container">
        <a href="{% url 'index' %}" class="navbar-brand">My <span class="text-info">real</span> trip</a>
        <div class="">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <p class="nav-link"><a href="{% url 'members:mypage' %}">{{ user }}</a>님 환영합니다.</p>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'members:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'members:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'members:signup' %}">Signup</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'popular-city-list' %}">티켓 검색</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'flight-list' %}">항공권 검색</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'country-list' %}">인기호텔 검색</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'city-list' %}">한인민박 검색</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'accom-search-list' %}">호텔 검색</a>
        </li>
    </ul>

{% endblock %}